### PR TITLE
fix: rework eth_call according to spec

### LINKED ISSUE #621: Rework `eth_call` endpoint
1. it should return contracts return value without transforming it (right now we have `to_string . decode`)
2. it should be able to return jsonrpc error on error, right now it returns Receipt.to_dict with successful status

### PR DESCRIPTION
**Pull request by kp2pml30**
Fixes #621

# What

- now eth_call returns base64 encoded calldata and rpc error on error

# Why

- to fix a bug

# Testing done

- tested the new feature manually
- integrations tests pass (except for one malformed...)

# Decisions made

# Checks

- [x] I have tested this code
- [x] I have reviewed my own PR
- [x] I have created an issue for this PR
- [x] I have set a descriptive PR title compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

# Reviewing tips

# User facing release notes

### CODE REVIEW

File: frontend/src/components/Simulator/ContractMethodItem.vue [hunk 1]
```diff
@@ -37,8 +38,13 @@ const handleCallReadMethod = async () => {
       }),
     );
 
-    responseMessage.value =
-      typeof result === 'string' ? result : JSON.stringify(result);
+    let repr: string;
+    if (typeof result === 'string') {
```
Comment (kp2pml30) [inline frontend/src/components/Simulator/ContractMethodItem.vue:42]: I think type annotations for callReadMethod are incorrect because it specifies that it returns `{ [key: string]: any }`

**Review by cristiam86 — APPROVED** [review]
